# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1

commands:
  poetry-build:
    description: Build packages using twine
    steps:
      - run:
          name: Installing poetry
          command: |
            pip install poetry
      - run:
          name: Building Package
          command: |
            poetry build
            poetry config pypi-token.pypi ${PYPI_TOKEN}

  poetry-publish:
    description: Build packages using twine
    steps:
      - run:
          name: Publishing Package
          command: |
            poetry --skip-existing publish
            

jobs:
  build-and-publish:
    docker:
      - image: cimg/python:3.11
    resource_class: small
    steps:
      - checkout
      - poetry-build
      - poetry-publish

workflows:
  package:
    jobs:
      - build-and-publish:
          context:
            - pypi
          filters:
            branches:
              only: main

